apiVersion: v2
name: do500
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
maintainers:
- name: eformat
- name: tylerauerbeck
- name: jacobsee
- name: jtudelag
- name: ckavili
- name: springdo
dependencies:
  - name: do500-subs
    version: "0.0.1"
    repository: "file://../do500-subs" #"https://redhat-cop.github.io/helm-charts"
    tags:
      - subs
