apiVersion: v2
name: do500
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.1
maintainers:
- name: eformat
- name: tylerauerbeck
- name: jacobsee
- name: jtudelag
- name: ckavili
- name: springdo
